---
abstract: ~
author:
  - 'Kazuho Oku'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::TCP: 0.15
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Server::Standalone::Prefork::Server::Starter
name: Plack-Server-Standalone-Prefork-Server-Starter
no_index:
  directory:
    - inc
    - t
recommends:
  HTTP::Parser::XS: 0
requires:
  Parallel::Prefork: 0.05
  Plack: 0.902
  Server::Starter: 0.05
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
